package vn.chatbot.dao;

import vn.chatbot.domain.CustomerLog;

public interface CustomerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    int insert(CustomerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    int insertSelective(CustomerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    CustomerLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    int updateByPrimaryKeySelective(CustomerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    int updateByPrimaryKey(CustomerLog record);
}