package vn.chatbot.dao;

import java.util.List;
import java.util.Map;

import vn.chatbot.domain.Member;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    Member selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    int updateByPrimaryKey(Member record);
    
    int updatePassword(Member record);

	Member getMemberByName(String username);

	Member getMemberByEmail(String email);
	
	List<Member> filter(Map<String, Object> parms);
}