package vn.chatbot.dao;

import vn.chatbot.domain.QaPair;

public interface QaPairMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_pair
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_pair
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    int insert(QaPair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_pair
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    int insertSelective(QaPair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_pair
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    QaPair selectByPrimaryKey(Integer id);
    QaPair selectByIdSolr(String idsolr);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_pair
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    int updateByPrimaryKeySelective(QaPair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_pair
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    int updateByPrimaryKey(QaPair record);
}