package vn.chatbot.dao;

import vn.chatbot.domain.QaSolr;

public interface QaSolrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_solr
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_solr
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    int insert(QaSolr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_solr
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    int insertSelective(QaSolr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_solr
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    QaSolr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_solr
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    int updateByPrimaryKeySelective(QaSolr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_solr
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    int updateByPrimaryKey(QaSolr record);
}