package vn.chatbot.dao;

import vn.chatbot.domain.SessionLog;

public interface SessionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    int insert(SessionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    int insertSelective(SessionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    SessionLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    int updateByPrimaryKeySelective(SessionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    int updateByPrimaryKey(SessionLog record);
}