package vn.chatbot.domain;

import java.util.Date;

public class CustomerLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.unikey
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private String unikey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.timestamp
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private Date timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.session_id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.question
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.answer
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private String organswer;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_log.answer
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.id
     *
     * @return the value of customer_log.id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.id
     *
     * @param id the value for customer_log.id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.unikey
     *
     * @return the value of customer_log.unikey
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public String getUnikey() {
        return unikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.unikey
     *
     * @param unikey the value for customer_log.unikey
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setUnikey(String unikey) {
        this.unikey = unikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.timestamp
     *
     * @return the value of customer_log.timestamp
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.timestamp
     *
     * @param timestamp the value for customer_log.timestamp
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.session_id
     *
     * @return the value of customer_log.session_id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.session_id
     *
     * @param sessionId the value for customer_log.session_id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.question
     *
     * @return the value of customer_log.question
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.question
     *
     * @param question the value for customer_log.question
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.organswer
     *
     * @return the value of customer_log.organswer
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_log.answer
     *
     * @return the value of customer_log.answer
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public String getAnswer() {
        return answer;
    }

    public String getOrganswer() {
		return organswer;
	}

	public void setOrganswer(String organswer) {
		this.organswer = organswer;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_log.answer
     *
     * @param answer the value for customer_log.answer
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }
}