package vn.chatbot.domain;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.user_id
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.fullname
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.active
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    private Integer active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.active_code
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    private String activeCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_id
     *
     * @return the value of member.user_id
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_id
     *
     * @param userId the value for member.user_id
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.fullname
     *
     * @return the value of member.fullname
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.fullname
     *
     * @param fullname the value for member.fullname
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.active
     *
     * @return the value of member.active
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.active
     *
     * @param active the value for member.active
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.active_code
     *
     * @return the value of member.active_code
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public String getActiveCode() {
        return activeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.active_code
     *
     * @param activeCode the value for member.active_code
     *
     * @mbggenerated Tue May 22 00:33:16 ICT 2018
     */
    public void setActiveCode(String activeCode) {
        this.activeCode = activeCode;
    }
}