package vn.chatbot.domain;

public class QaPair {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_pair.id
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    private Integer id;
    private String idsolr;
    private String sessionid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_pair.question
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    private Integer countmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_pair.count
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    private Integer countdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_pair.id
     *
     * @return the value of qa_pair.id
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_pair.id
     *
     * @param id the value for qa_pair.id
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

	public String getIdsolr() {
		return idsolr;
	}

	public void setIdsolr(String idsolr) {
		this.idsolr = idsolr;
	}

	public String getSessionid() {
		return sessionid;
	}

	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	public Integer getCountmod() {
		return countmod;
	}

	public void setCountmod(Integer countmod) {
		this.countmod = countmod;
	}

	public Integer getCountdel() {
		return countdel;
	}

	public void setCountdel(Integer countdel) {
		this.countdel = countdel;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_pair.question
     *
     * @return the value of qa_pair.question
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_pair.question
     *
     * @param question the value for qa_pair.question
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_pair.count
     *
     * @return the value of qa_pair.count
     *
     * @mbggenerated Tue May 29 05:53:01 ICT 2018
     */
    
}