package vn.chatbot.domain;

public class QaSolr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_solr.id
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_solr.question
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_solr.answer
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_solr.id
     *
     * @return the value of qa_solr.id
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_solr.id
     *
     * @param id the value for qa_solr.id
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_solr.question
     *
     * @return the value of qa_solr.question
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_solr.question
     *
     * @param question the value for qa_solr.question
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_solr.answer
     *
     * @return the value of qa_solr.answer
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_solr.answer
     *
     * @param answer the value for qa_solr.answer
     *
     * @mbggenerated Tue Jun 12 00:35:56 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }
}