package vn.chatbot.domain;

import java.util.Date;

public class SessionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.session_id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.user_id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.start_time
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.end_time
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.id
     *
     * @return the value of session_log.id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.id
     *
     * @param id the value for session_log.id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.session_id
     *
     * @return the value of session_log.session_id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.session_id
     *
     * @param sessionId the value for session_log.session_id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.user_id
     *
     * @return the value of session_log.user_id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.user_id
     *
     * @param userId the value for session_log.user_id
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.start_time
     *
     * @return the value of session_log.start_time
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.start_time
     *
     * @param startTime the value for session_log.start_time
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.end_time
     *
     * @return the value of session_log.end_time
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.end_time
     *
     * @param endTime the value for session_log.end_time
     *
     * @mbggenerated Sun Apr 22 09:34:12 ICT 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}